import { Link } from 'react-router-dom'
import { MapPin, CalendarDays, Headphones, Route, ArrowUpRight } from 'lucide-react'
const faq=[['How do I book a car?','Choose your pickup location and dates, search available cars, and complete the booking form. Our team will help confirm your booking.'],['Where can I collect and return my car?','Choose from the pickup locations in the search form. You can select a different return location when planning your trip.'],['How can I see the rental price?','Search with your dates to see a quote. Your booking summary includes rental and delivery charges.'],['How do I contact Zudo Cars?','Call +91 81119 46664 or use our Contact page for booking assistance.']]
export default function RentalSections(){return <div className="rental-content">
  <section className="rental-benefits"><h2>Why rent a car with Zudo Cars?</h2><div>{[[MapPin,'Choose your location','Pick up and return at locations across Kerala.'],[CalendarDays,'Plan your own trip','Choose the dates and times that suit your journey.'],[Headphones,'Talk to our team','Get help with your booking and rental details.'],[Route,'See the full quote','Review rental and delivery charges before booking.']].map(([Icon,title,copy])=><article key={title}><Icon size={42}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="rental-collections"><h2>Explore Kerala your way</h2><p>A drive for every destination.</p><div>{[['City drives','Kovalam.jpg'],['Weekend escapes','Munnar.jpg'],['Family journeys','Alleppey.jpg'],['Longer stays','wayannad.jpg']].map(([label,image])=><Link to="/cars" key={label}><img src={`/images/${image}`} alt={label}/><h3>{label}<ArrowUpRight/></h3><p>Explore available cars</p></Link>)}</div></section>
  <section className="rental-steps"><h2>4 steps — and you're on your way</h2><div>{[['Find your car','Search with your location and travel dates.'],['Choose your vehicle','Pick an available car for your journey.'],['Book your drive','Submit your details and review the estimate.'],['Collect and go','Confirm with our team and collect your car.']].map(([title,copy],i)=><article key={title}><span>{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section id="faq" className="rental-faq"><h2>Frequently asked questions</h2>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
</div>}
