import { useState } from "react";

const queue = [
  { vehicle: "Alto K10", reg: "KL07DD8525", type: "General", mileage: "24,500", due: "28 Sep", priority: "High", status: "Due", centre: "Zudo Service" },
  { vehicle: "Creta", reg: "KL01XX1234", type: "Oil Change", mileage: "31,200", due: "30 Sep", priority: "Medium", status: "Scheduled", centre: "—" },
];

function Services() {
  const [tab, setTab] = useState("Service Queue");
  const tabs = ["Service Queue", "Service History", "Service Centres"];
  return <div className="min-h-screen bg-[#f6f8fb] text-slate-950"><aside className="fixed inset-y-0 left-0 hidden w-64 bg-[#101114] px-6 py-8 text-white lg:block"><div className="mb-14 text-2xl font-extrabold">Zudocars<span className="text-teal-400">.</span><p className="mt-1 text-[10px] tracking-[0.25em] text-slate-400">SELF-DRIVE KERALA</p></div><nav className="space-y-3 text-sm font-semibold"><a href="/dashboard" className="block rounded-xl px-4 py-3 text-slate-300">Overview</a><a href="/dashboard/maintenance" className="block rounded-xl px-4 py-3 text-slate-300">Maintenance</a><a href="/dashboard/services" className="block rounded-xl bg-teal-600 px-4 py-3">Services</a><a href="/dashboard" className="block rounded-xl px-4 py-3 text-slate-300">Fleet</a></nav></aside><main className="lg:ml-64"><header className="border-b border-slate-200 bg-white px-6 py-7 lg:px-10"><p className="text-xs font-bold tracking-[0.25em] text-teal-700">ZUDOCARS SELF-DRIVE</p><h1 className="mt-2 text-3xl font-extrabold">Service management</h1><p className="mt-1 text-slate-500">Coordinate servicing, history and service-centre performance.</p></header><div className="p-6 lg:p-10"><div className="mb-6 flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-2 shadow-sm">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === item ? "bg-teal-600 text-white" : "text-slate-500 hover:bg-slate-100"}`}>{item}</button>)}</div>{tab === "Service Queue" && <Queue />}{tab === "Service History" && <History />}{tab === "Service Centres" && <Centres />}</div></main></div>;
}

function Queue() { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Service queue</h2><p className="mt-1 text-sm text-slate-500">A ready-to-connect workspace for due and scheduled maintenance.</p></div><button className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-bold text-white">+ Add service</button></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-400"><tr>{["Vehicle", "Registration", "Service", "Mileage", "Due", "Priority", "Status", "Centre"].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody>{queue.map((item) => <tr key={item.reg} className="border-b border-slate-100"><td className="px-3 py-4 font-bold">{item.vehicle}</td><td className="px-3 py-4 text-slate-500">{item.reg}</td><td className="px-3 py-4">{item.type}</td><td className="px-3 py-4 text-slate-500">{item.mileage} km</td><td className="px-3 py-4">{item.due}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.priority === "High" ? "bg-red-50 text-red-600" : "bg-amber-50 text-amber-600"}`}>{item.priority}</span></td><td className="px-3 py-4"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-700">{item.status}</span></td><td className="px-3 py-4 text-slate-500">{item.centre}</td></tr>)}</tbody></table></div></section>; }
function History() { return <section className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Service history</h2><p className="mt-1 text-sm text-slate-500">Select a vehicle to review its health and timeline.</p><button className="mt-6 w-full rounded-xl border border-teal-200 bg-teal-50 p-4 text-left"><strong>Alto K10</strong><span className="mt-1 block text-sm text-slate-500">KL07DD8525</span></button></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Alto K10</h2><p className="text-sm text-slate-500">KL07DD8525</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Info label="Current mileage" value="24,500 km" /><Info label="Last service" value="12 Aug 2026" /><Info label="Next service" value="28 Sep 2026" /><Info label="Total service cost" value="₹18,450" /></div><h3 className="mt-8 font-bold">Service timeline</h3><div className="mt-4 space-y-4 border-l-2 border-teal-100 pl-5"><Info label="Sep 2026 · General Service" value="24,500 km · ₹4,850" /><Info label="Aug 2026 · Oil + Filter" value="21,800 km · ₹2,400" /><Info label="Jun 2026 · Brake inspection" value="19,200 km · ₹1,800" /></div><p className="mt-6 text-sm text-slate-400">Parts, invoices, labour, technician, warranty, notes and downtime fields are ready for API integration.</p></div></section>; }
function Info({ label, value }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
function Centres() { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Service centres</h2><p className="mt-1 text-sm text-slate-500">Track centre performance as partner data becomes available.</p><div className="mt-6 max-w-md rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-bold">Zudo Service Centre</h3><div className="mt-6 grid grid-cols-2 gap-4"><Info label="Vehicles serviced" value="126" /><Info label="Avg. service cost" value="₹4,820" /><Info label="Avg. turnaround" value="1.8 days" /><Info label="Repeat issues" value="7" /></div><div className="mt-4 rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Quality score</p><p className="mt-1 font-bold text-slate-400">—</p></div></div></section>; }

export default Services;
